name       : libgdata
version    : 0.17.13
release    : 12
source     :
    - https://download.gnome.org/sources/libgdata/0.17/libgdata-0.17.13.tar.xz : eab9ef792c3c2b9ece19d45aea15225aba8df2521bc12785b1b2d3318d8c472e
license    : LGPL-2.1-only
component  : desktop.gnome.core
summary    : GData Protocol support
description: |
    libgdata is a GLib-based library for accessing online service APIs using the GData protocol — most notably, Google's services. It provides APIs to access the common Google services, and has full asynchronous support.libgdata is a GLib-based library for accessing online service APIs using the GData protocol — most notably, Google's services. It provides APIs to access the common Google services, and has full asynchronous support.
builddeps  :
    - pkgconfig(gcr-base-3)
    - pkgconfig(goa-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(oauth)
    - gtk-doc
    - vala
setup      : |
    %meson_configure -Dalways_build_tests=false -Doauth1=enabled
build      : |
    %ninja_build
install    : |
    %ninja_install
