name       : libgdata
version    : 0.17.10
release    : 9
source     :
    - git|https://gitlab.gnome.org/GNOME/libgdata.git : b653f602b3c2b518101c5d909e1651534c22757a
license    : LGPL-2.1-only
component  : desktop.gnome.core
summary    : GData Protocol support
description: |
    libgdata is a GLib-based library for accessing online service APIs using the GData protocol — most notably, Google's services. It provides APIs to access the common Google services, and has full asynchronous support.libgdata is a GLib-based library for accessing online service APIs using the GData protocol — most notably, Google's services. It provides APIs to access the common Google services, and has full asynchronous support.
builddeps  :
    - pkgconfig(gcr-base-3)
    - pkgconfig(goa-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(oauth)
    - gtk-doc
    - vala
setup      : |
    %meson_configure -Dalways_build_tests=false -Dinstalled_tests=false
build      : |
    %ninja_build
install    : |
    %ninja_install
