name       : libgdata
version    : 0.18.1
release    : 15
source     :
    - https://download.gnome.org/sources/libgdata/0.18/libgdata-0.18.1.tar.xz : dd8592eeb6512ad0a8cf5c8be8c72e76f74bfe6b23e4dd93f0756ee0716804c7
license    : LGPL-2.1-only
component  : desktop.gnome.core
summary    : GData Protocol support
description: |
    libgdata is a GLib-based library for accessing online service APIs using the GData protocol — most notably, Google's services. It provides APIs to access the common Google services, and has full asynchronous support.libgdata is a GLib-based library for accessing online service APIs using the GData protocol — most notably, Google's services. It provides APIs to access the common Google services, and has full asynchronous support.
builddeps  :
    - pkgconfig(gcr-base-3)
    - pkgconfig(goa-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(oauth)
    - gtk-doc
    - vala
setup      : |
    %meson_configure -Dalways_build_tests=false -Doauth1=enabled
build      : |
    %ninja_build
install    : |
    %ninja_install
