name       : libgdata
version    : 0.17.9
release    : 6
source     :
    - https://download.gnome.org/sources/libgdata/0.17/libgdata-0.17.9.tar.xz : 85c4f7674c0098ffaf060ae01b6b832cb277b3673d54ace3bdedaad6b127453a
license    : LGPL-2.1
component  : desktop.gnome.core
summary    : GData Protocol support
description: |
    libgdata is a GLib-based library for accessing online service APIs using the GData protocol — most notably, Google's services. It provides APIs to access the common Google services, and has full asynchronous support.libgdata is a GLib-based library for accessing online service APIs using the GData protocol — most notably, Google's services. It provides APIs to access the common Google services, and has full asynchronous support.
builddeps  :
    - pkgconfig(gcr-base-3)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(goa-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libuhttpmock-0.0)
    - pkgconfig(oauth)
    - vala
setup      : |
    %configure --disable-static \
               --disable-tests
build      : |
    %make
install    : |
    %make_install
