name       : libgdata
version    : 0.17.8
release    : 5
source     :
    - https://ftp.gnome.org/pub/gnome/sources/libgdata/0.17/libgdata-0.17.8.tar.xz : e5e735bfac219c6cbe4a14df481cb3cb4b1c4b8b5e70f9a105a884035bc3a161
license    : LGPL-2.1
component  : desktop.gnome.core
summary    : GData Protocol support
description: |
    libgdata is a GLib-based library for accessing online service APIs using the GData protocol — most notably, Google's services. It provides APIs to access the common Google services, and has full asynchronous support.libgdata is a GLib-based library for accessing online service APIs using the GData protocol — most notably, Google's services. It provides APIs to access the common Google services, and has full asynchronous support.
builddeps  :
    - pkgconfig(gcr-base-3)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(goa-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libuhttpmock-0.0)
    - pkgconfig(oauth)
    - vala
setup      : |
    %configure --disable-static \
               --disable-tests
build      : |
    %make
install    : |
    %make_install
